export const cities = [
  'Manila',
  'Quezon City',
  'Cebu City',
  'Davao City',
  'Makati',
  'Taguig',
  'Pasig',
  'Cagayan de Oro',
  'Iloilo City',
  'Bacolod',
  'Baguio',
  'Zamboanga City',
  'General Santos',
  'Antipolo',
  'Batangas City',
  'Naga',
  'Olongapo',
  'Tacloban',
  'Tagaytay',
  'Laoag',
];