export const services = [
  {
    id: 1,
    name: 'BuildMart Philippines',
    category: 'Construction Materials',
    rating: 4.8,
    reviews: 156,
    location: 'Makati City',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80',
    isVerified: true,
    followers: 1240,
    description: 'Complete construction materials supplier with quality products and competitive prices.',
    services: ['Cement', 'Steel Bars', 'Tiles', 'Paint', 'Hardware'],
    phone: '+63 912 345 6789',
    email: 'info@buildmart.ph',
    website: 'www.buildmart.ph'
  },
  {
    id: 2,
    name: 'Elite Contractors Inc.',
    category: 'General Contracting',
    rating: 4.9,
    reviews: 89,
    location: 'Quezon City',
    image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80',
    isVerified: true,
    followers: 856,
    description: 'Professional construction and renovation services for residential and commercial projects.',
    services: ['Construction', 'Renovation', 'Project Management', 'Design-Build'],
    phone: '+63 917 234 5678',
    email: 'contact@elitecontractors.ph',
    website: 'www.elitecontractors.ph'
  },
  {
    id: 3,
    name: 'PowerTech Electrical',
    category: 'Electrical Services',
    rating: 4.7,
    reviews: 124,
    location: 'Taguig City',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80',
    isVerified: false,
    followers: 432,
    description: 'Licensed electrical contractors specializing in residential and commercial electrical work.',
    services: ['Wiring', 'Panel Installation', 'Lighting', 'Electrical Repair'],
    phone: '+63 918 345 6789',
    email: 'service@powertech.ph',
    website: 'www.powertech.ph'
  },
  {
    id: 4,
    name: 'AquaFlow Plumbing',
    category: 'Plumbing Services',
    rating: 4.6,
    reviews: 98,
    location: 'Pasig City',
    image: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80',
    isVerified: true,
    followers: 567,
    description: 'Expert plumbing services for all your water and drainage needs.',
    services: ['Pipe Installation', 'Leak Repair', 'Drain Cleaning', 'Water Heater'],
    phone: '+63 919 456 7890',
    email: 'info@aquaflow.ph',
    website: 'www.aquaflow.ph'
  },
  {
    id: 5,
    name: 'GreenScape Landscaping',
    category: 'Landscaping',
    rating: 4.8,
    reviews: 76,
    location: 'Muntinlupa City',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80',
    isVerified: true,
    followers: 789,
    description: 'Professional landscaping and garden design services for beautiful outdoor spaces.',
    services: ['Garden Design', 'Lawn Care', 'Tree Services', 'Irrigation'],
    phone: '+63 920 567 8901',
    email: 'design@greenscape.ph',
    website: 'www.greenscape.ph'
  },
  {
    id: 6,
    name: 'TileWorld Premium',
    category: 'Tiles & Flooring',
    rating: 4.5,
    reviews: 143,
    location: 'Paranaque City',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80',
    isVerified: false,
    followers: 623,
    description: 'Premium tiles and flooring materials with professional installation services.',
    services: ['Ceramic Tiles', 'Marble', 'Vinyl Flooring', 'Installation'],
    phone: '+63 921 678 9012',
    email: 'sales@tileworld.ph',
    website: 'www.tileworld.ph'
  },
  {
    id: 7,
    name: 'SteelCraft Fabrication',
    category: 'Steel Fabrication',
    rating: 4.7,
    reviews: 67,
    location: 'Las Pinas City',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80',
    isVerified: true,
    followers: 445,
    description: 'Custom steel fabrication and metalwork for construction and architectural projects.',
    services: ['Steel Fabrication', 'Welding', 'Metal Gates', 'Structural Steel'],
    phone: '+63 922 789 0123',
    email: 'orders@steelcraft.ph',
    website: 'www.steelcraft.ph'
  },
  {
    id: 8,
    name: 'CoolAir HVAC Solutions',
    category: 'HVAC Services',
    rating: 4.6,
    reviews: 112,
    location: 'Marikina City',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80',
    isVerified: true,
    followers: 678,
    description: 'Professional HVAC installation, maintenance, and repair services.',
    services: ['AC Installation', 'Ventilation', 'Maintenance', 'Repair'],
    phone: '+63 923 890 1234',
    email: 'service@coolair.ph',
    website: 'www.coolair.ph'
  }
];