export const specializations = [
  'Residential Architecture',
  'Commercial Architecture',
  'Interior Design',
  'Landscape Architecture',
  'Urban Planning',
  'Industrial Architecture',
  'Sustainable/Green Architecture',
  'Historic Preservation',
  'Institutional Architecture',
  'Hospitality Architecture',
  'Healthcare Architecture',
  'Retail Architecture',
  'Mixed-Use Development',
  'Transportation Architecture',
  'Educational Facilities',
  'Religious Architecture',
  'Cultural Architecture',
  'Recreational Architecture',
];